# fly.toml app configuration file generated for web-server-personal on 2024-12-29T13:30:17-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'web-server-personal'
primary_region = 'sjc'

[build]
include = ["html/**", "static/**"]

[env]
  HOST = "0.0.0.0"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443